import type { Field, FieldOption } from "./../types/data";

export const options: FieldOption[] = [
  { value: "AF" },
  { value: "AX" },
  { value: "AL" },
  { value: "DZ" },
  { value: "AD" },
  { value: "AO" },
  { value: "AI" },
  { value: "AQ" },
  { value: "AG" },
  { value: "AR" },
  { value: "AM" },
  { value: "AW" },
  { value: "AC" },
  { value: "AU" },
  { value: "AT" },
  { value: "AZ" },
  { value: "BS" },
  { value: "BH" },
  { value: "BD" },
  { value: "BB" },
  { value: "BY" },
  { value: "BE" },
  { value: "BZ" },
  { value: "BJ" },
  { value: "BM" },
  { value: "BT" },
  { value: "BO" },
  { value: "BA" },
  { value: "BW" },
  { value: "BV" },
  { value: "BR" },
  { value: "IO" },
  { value: "VG" },
  { value: "BN" },
  { value: "BG" },
  { value: "BF" },
  { value: "BI" },
  { value: "KH" },
  { value: "CM" },
  { value: "CA" },
  { value: "CV" },
  { value: "BQ" },
  { value: "KY" },
  { value: "CF" },
  { value: "TD" },
  { value: "CL" },
  { value: "CN" },
  { value: "CO" },
  { value: "KM" },
  { value: "CG" },
  { value: "CD" },
  { value: "CK" },
  { value: "CR" },
  { value: "CI" },
  { value: "HR" },
  { value: "CW" },
  { value: "CY" },
  { value: "CZ" },
  { value: "DK" },
  { value: "DJ" },
  { value: "DM" },
  { value: "DO" },
  { value: "EC" },
  { value: "EG" },
  { value: "SV" },
  { value: "GQ" },
  { value: "ER" },
  { value: "EE" },
  { value: "SZ" },
  { value: "ET" },
  { value: "FK" },
  { value: "FO" },
  { value: "FJ" },
  { value: "FI" },
  { value: "FR" },
  { value: "GF" },
  { value: "PF" },
  { value: "TF" },
  { value: "GA" },
  { value: "GM" },
  { value: "GE" },
  { value: "DE" },
  { value: "GH" },
  { value: "GI" },
  { value: "GR" },
  { value: "GL" },
  { value: "GD" },
  { value: "GP" },
  { value: "GU" },
  { value: "GT" },
  { value: "GG" },
  { value: "GN" },
  { value: "GW" },
  { value: "GY" },
  { value: "HT" },
  { value: "HN" },
  { value: "HK" },
  { value: "HU" },
  { value: "IS" },
  { value: "IN" },
  { value: "ID" },
  { value: "IQ" },
  { value: "IE" },
  { value: "IM" },
  { value: "IL" },
  { value: "IT" },
  { value: "JM" },
  { value: "JP" },
  { value: "JE" },
  { value: "JO" },
  { value: "KZ" },
  { value: "KE" },
  { value: "KI" },
  { value: "XK" },
  { value: "KW" },
  { value: "KG" },
  { value: "LA" },
  { value: "LV" },
  { value: "LB" },
  { value: "LS" },
  { value: "LR" },
  { value: "LY" },
  { value: "LI" },
  { value: "LT" },
  { value: "LU" },
  { value: "MO" },
  { value: "MG" },
  { value: "MW" },
  { value: "MY" },
  { value: "MV" },
  { value: "ML" },
  { value: "MT" },
  { value: "MQ" },
  { value: "MR" },
  { value: "MU" },
  { value: "YT" },
  { value: "MX" },
  { value: "MD" },
  { value: "MC" },
  { value: "MN" },
  { value: "ME" },
  { value: "MS" },
  { value: "MA" },
  { value: "MZ" },
  { value: "MM" },
  { value: "NA" },
  { value: "NR" },
  { value: "NP" },
  { value: "NL" },
  { value: "NC" },
  { value: "NZ" },
  { value: "NI" },
  { value: "NE" },
  { value: "NG" },
  { value: "NU" },
  { value: "MK" },
  { value: "NO" },
  { value: "OM" },
  { value: "PK" },
  { value: "PS" },
  { value: "PA" },
  { value: "PG" },
  { value: "PY" },
  { value: "PE" },
  { value: "PH" },
  { value: "PN" },
  { value: "PL" },
  { value: "PT" },
  { value: "PR" },
  { value: "QA" },
  { value: "RE" },
  { value: "RO" },
  { value: "RU" },
  { value: "RW" },
  { value: "WS" },
  { value: "SM" },
  { value: "ST" },
  { value: "SA" },
  { value: "SN" },
  { value: "RS" },
  { value: "SC" },
  { value: "SL" },
  { value: "SG" },
  { value: "SX" },
  { value: "SK" },
  { value: "SI" },
  { value: "SB" },
  { value: "SO" },
  { value: "ZA" },
  { value: "GS" },
  { value: "KR" },
  { value: "SS" },
  { value: "ES" },
  { value: "LK" },
  { value: "BL" },
  { value: "SH" },
  { value: "KN" },
  { value: "LC" },
  { value: "MF" },
  { value: "PM" },
  { value: "VC" },
  { value: "SD" },
  { value: "SR" },
  { value: "SJ" },
  { value: "SE" },
  { value: "CH" },
  { value: "TW" },
  { value: "TJ" },
  { value: "TZ" },
  { value: "TH" },
  { value: "TL" },
  { value: "TG" },
  { value: "TK" },
  { value: "TO" },
  { value: "TT" },
  { value: "TA" },
  { value: "TN" },
  { value: "TR" },
  { value: "TM" },
  { value: "TC" },
  { value: "TV" },
  { value: "UG" },
  { value: "UA" },
  { value: "AE" },
  { value: "GB" },
  { value: "US" },
  { value: "UY" },
  { value: "UZ" },
  { value: "VU" },
  { value: "VA" },
  { value: "VE" },
  { value: "VN" },
  { value: "WF" },
  { value: "EH" },
  { value: "YE" },
  { value: "ZM" },
  { value: "ZW" }
];

export function shippingDataToBillingData(shippingData: Record<string, unknown>): Record<string, unknown> {
  const billingData: Record<string, unknown> = {};
  const mapping: Record<string, string> = {
    shipping_country: 'billing_country',
    shipping_address_line_1: 'billing_address_line_1',
    shipping_address_line_2: 'billing_address_line_2',
    shipping_postal_code: 'billing_postal_code',
    shipping_city: 'billing_city',
  };

  for (const [shippingKey, billingKey] of Object.entries(mapping)) {
    if (shippingKey in shippingData) {
      billingData[billingKey] = shippingData[shippingKey];
    }
  }

  return billingData;
}

export default function(): Field[] {
  return [
    { name: 'billing_country', type: 'select', options, validation: { required: [] } },
    { name: 'billing_address_line_1', type: 'text', validation: { required: [] } },
    { name: 'billing_address_line_2', type: 'text', validation: { required: [] } },
    { name: 'billing_postal_code', type: 'text', validation: { required: [] } },
    { name: 'billing_city', type: 'text', validation: { required: [] } },
  ]
}
